Add preview of Attachment using BigPicture.js (2.6.1)
redmica/redmica_ui_extension pull request #31
Opened 2022-02-28 03:31 UTC by takenory

I propose a feature to preview Attachment using BigPicture.js.
This feature allows you to preview image files, audio files, video files, and PDF files without screen transitions.

2022-02-28 05:45 UTC, ishikawa999 requested changes

2022-02-28 05:45 UTC, ishikawa999 commented on test/helpers/application_helper_patch_test.rb
> +  end
https://github.com/redmica/redmica_ui_extension/pull/31/checks

GitHub Actionsで自動実行しているテストではここのあたりのテストが失敗しているようです。  
高木さんの手元では再現できますか？

おそらくattachmentsのfixturesが無いこと( https://github.com/redmica/redmica_ui_extension/pull/31/files#diff-a5ac8b58555b79516fb065069fb321e0803ad5050cda5d3c0a9bab3e2b54487eR9 )が原因なので、rake db:migrate:resetした上でこのファイルだけを指定してテストすれば再現できそうです。

2022-02-28 05:53 UTC, ishikawa999 requested changes

2022-02-28 05:53 UTC, ishikawa999 commented on lib/preview_attachment/application_helper_patch.rb
> +                :onclick => 'previewAttachment(this)').html_safe + original_link
```
link_to('', '#', :class => 'icon-only icon-zoom-in',
                :data => { :bp => filename, :bp_src => bp_src, :url => url },
                :onclick => 'previewAttachment(this)')
```
も
`original_link` もActiveSupport::SafeBufferのオブジェクトなので、html_safeしなくても結合できると思います

2022-02-28 06:26 UTC, ishikawa999 commented on assets/preview_attachment/javascripts/BigPicture.min.js
> +var BigPicture=function(){var t,n,e,o,i,r,a,c,p,s,l,d,u,f,m,b,g,h,x,v,y,w,_,T,k,M,S,L,E,A,H,z,C,I=[],D={},O="appendChild",V="createElement",N="removeChild";function W(){var n=t.getBoundingClientRect(
https://github.com/redmica/redmica_ui_extension#libraries-included に他のライブラリの情報を書いているので、bigpictureについても追加していただきたいです

2022-02-28 07:15 UTC, takenory commented on assets/preview_attachment/javascripts/BigPicture.min.js
> +var BigPicture=function(){var t,n,e,o,i,r,a,c,p,s,l,d,u,f,m,b,g,h,x,v,y,w,_,T,k,M,S,L,E,A,H,z,C,I=[],D={},O="appendChild",V="createElement",N="removeChild";function W(){var n=t.getBoundingClientRect(
追記します！

2022-02-28 08:45 UTC, takenory commented on lib/preview_attachment/application_helper_patch.rb
> +                :onclick => 'previewAttachment(this)').html_safe + original_link
@ishikawa999 
ご指摘ありがとうございます！

2022-02-28 09:10 UTC, takenory commented on lib/preview_attachment/application_helper_patch.rb
> +                :onclick => 'previewAttachment(this)').html_safe + original_link
@ishikawa999 
本件、以下のコミットで対処しました。
https://github.com/redmica/redmica_ui_extension/pull/31/commits/d63cb338cdfaf6927228c3192b091bf5e29ef1e5

2022-02-28 09:11 UTC, takenory commented on test/helpers/application_helper_patch_test.rb
> +  end
@ishikawa999 
本件、以下のコミットで対処しました。
https://github.com/redmica/redmica_ui_extension/pull/31/commits/86128870994d5fc7c843f41582a54f03e62aa130

2022-02-28 09:16 UTC, takenory commented on assets/preview_attachment/javascripts/BigPicture.min.js
> +var BigPicture=function(){var t,n,e,o,i,r,a,c,p,s,l,d,u,f,m,b,g,h,x,v,y,w,_,T,k,M,S,L,E,A,H,z,C,I=[],D={},O="appendChild",V="createElement",N="removeChild";function W(){var n=t.getBoundingClientRect(
@ishikawa999 
以下のコミットで追記しました。
https://github.com/redmica/redmica_ui_extension/pull/31/commits/23acaab8ccbc7f151f7e0ee04eeb615be1eac14a
ご確認ください。

2022-02-28 23:26 UTC, ishikawa999 commented on lib/preview_attachment/application_helper_patch.rb
> +                :onclick => 'previewAttachment(this)').html_safe + original_link
確認しました。良いと思います。

2022-02-28 23:27 UTC, ishikawa999 commented on assets/preview_attachment/javascripts/BigPicture.min.js
> +var BigPicture=function(){var t,n,e,o,i,r,a,c,p,s,l,d,u,f,m,b,g,h,x,v,y,w,_,T,k,M,S,L,E,A,H,z,C,I=[],D={},O="appendChild",V="createElement",N="removeChild";function W(){var n=t.getBoundingClientRect(
ご対応いただきありがとうございました。

2022-02-28 23:28 UTC, ishikawa999 commented on test/helpers/application_helper_patch_test.rb
> +  end
テストがうまく動くようになっていることを確認できました。ありがとうございます。

2022-03-01 02:43 UTC, ishikawa999 approved these changes

2022-03-07 02:48 UTC, yui-har reviewed
@takenory コメント欄の添付ファイルをBigPictureで表示後、BigPictureを閉じるとチケット画面のトップに戻ります。画面中段のコメント欄のBigPicture表示は使いづらく感じます。
画面遷移せずクリックした箇所で留まることは難しいのでしょうか。

2022-03-07 03:03 UTC, takenory commented
@yui-har wrote:
> コメント欄の添付ファイルをBigPictureで表示後、BigPictureを閉じるとチケット画面のトップに戻ります。

ほんとですね；よく見ると表示する段階で画面のトップに移動してますね;
そして、虫眼鏡アイコンをマウスオーバーしてみると...
`http://localhost:3000/issues/1#` のようにリンクしてることがわかりました。
画面遷移しないよう見直します！

2022-03-07 06:37 UTC, takenory commented
@yui-har 
> コメント欄の添付ファイルをBigPictureで表示後、BigPictureを閉じるとチケット画面のトップに戻ります。

以下のコミットで修正しました。ご確認ください。
https://github.com/redmica/redmica_ui_extension/pull/31/commits/f9dba128401173a77e37eabc0fbdab8a0ff6401f

2022-03-07 06:45 UTC, takenory commented
@yui-har 
https://github.com/redmica/redmica_ui_extension/pull/31#issuecomment-1060241684 の件、テストの修正が漏れていました;
テストを修正してから再度レビューの依頼をさせてください。

2022-03-07 07:03 UTC, takenory commented
@yui-har 
> コメント欄の添付ファイルをBigPictureで表示後、BigPictureを閉じるとチケット画面のトップに戻ります。

以下のコミットで修正しました。ご確認ください。
* https://github.com/redmica/redmica_ui_extension/pull/31/commits/f9dba128401173a77e37eabc0fbdab8a0ff6401f
* https://github.com/redmica/redmica_ui_extension/pull/31/commits/100d3597ca99f461e64858cd4ace59cf2347d358

2022-03-07 08:01 UTC, yui-har commented on test/helpers/application_helper_patch_test.rb
> +                                 :onclick => 'previewAttachment(this)').html_safe
@takenory d63cb33 でhtml_safeを削除していますけど、このhtml_safeは削除しなくてよいのでしょうか。

2022-03-07 08:06 UTC, yui-har commented
> @yui-har
> 
> > コメント欄の添付ファイルをBigPictureで表示後、BigPictureを閉じるとチケット画面のトップに戻ります。
> 
> 以下のコミットで修正しました。ご確認ください。

@takenory チケット画面がトップに移動すること無く、クリックした箇所でBigPictureが表示されることを確認しました。

2022-03-07 08:08 UTC, takenory commented on test/helpers/application_helper_patch_test.rb
> +                                 :onclick => 'previewAttachment(this)').html_safe
@yui-har ご指摘ありがとうございます。削除する方が適切です。100d359 で対処しました。

2022-03-07 08:27 UTC, yui-har commented on test/helpers/application_helper_patch_test.rb
> +                                 :onclick => 'previewAttachment(this)').html_safe
@takenory 確認しました。OKです。

2022-03-07 08:28 UTC, yui-har approved these changes
@takenory BigPictureが動作することを確認しました。マージして良いと思います。

2022-03-07 08:36 UTC, takenory commented
@ishikawa999 @yui-har レビューいただきありがとうございました。
@ishikawa999 マージをお願いいたします。

2022-03-08 00:59 UTC, merged

2022-03-08 01:00 UTC, ishikawa999 commented
マージしました。