Add Burndown chart on version detail
redmica/redmica_ui_extension pull request #6
Opened 2021-03-11 05:36 UTC by takenory

I propose a feature to visualize the changes of Open / Close issues in the version detail using 'Burndown chart'.
![image](https://user-images.githubusercontent.com/926014/110740871-129e1080-8277-11eb-9073-db3b9c967105.png)

2021-03-15 06:42 UTC, ishikawa999 reviewed
現時点で気になった点について記載しました。(まだ全部は見終えていません)

2021-03-15 06:42 UTC, ishikawa999 commented on assets/burndown_chart/javascripts/burndown_chart.js
> +          time: { unit: "day", displayFormats: { day: 'YYYY-MM-DD' } },
日付のフォーマットは現在YYYY-MM-DDですが、Setting['date_format']のフォーマットに合わせた方が良い気がします。  
(プラグインとしては正直そんなに気になりませんが、パッチも出しているため)

2021-03-15 06:42 UTC, ishikawa999 commented on lib/burndown_chart/versions_helper_patch.rb
> +        open = chart_start_date.step(line_end_date, step_size).collect{ |d| { :t => d.to_s, :y => issues.where("#{Issue.table_name}.created_on<=?", d.end_of_day).count - issues.open(false).where("#{I
total_closedとopenについて、
* line_start_dateが2021/3/8
* line_end_dateがUser.current.today(2021/3/15)
* stepが5

という状態で2021/3/15時点でチケットをクローズしたり追加した場合、それがチャートに反映されないことが分かりました。

これは、`chart_start_date.step(line_end_date, step_size)`が上のような例では `[Mon, 08 Mar 2021, Sat, 13 Mar 2021]` のようなEnumeratorを返してしまうため、2021/3/13〜2021/3/15の期間中の件数がチェックされないためだと思います。  
もう少し良いやり方もあるかもしれませんが、次のsuggestionのように `line_end_date + (step_size - 1)` を基準に変えることで、件数をチェックする範囲が[Mon, 08 Mar 2021, Sat, 13 Mar 2021, Thu, 18 Mar 2021]に変わって2021/3/15の変更もチャートに反映されるようになります。  
(ただ、そう変更した場合User.current.todayより先の日付の場所に点が入ることになるので、それも少し違和感につながりそうではあります)

```suggestion
        total_closed = chart_start_date.step(line_end_date + (step_size - 1), step_size).collect{ |d| { :t => d.to_s, :y => issues.where("#{Issue.table_name}.closed_on IS NULL OR #{Issue.table_name}.closed_on>=?", d.end_of_day).count } }
        open = chart_start_date.step(line_end_date + (step_size - 1), step_size).collect{ |d| { :t => d.to_s, :y => issues.where("#{Issue.table_name}.created_on<=?", d.end_of_day).count - issues.open(false).where("#{Issue.table_name}.closed_on<=?", d.end_of_day).count } }
```

2021-03-15 07:20 UTC, ishikawa999 commented
線の色が結構薄くて見づらく感じました。背景とのコントラスト比が結構低いようなので、もう少しはっきりした色に変えても良いんじゃないかなと思います。  
(絶対変更しないといけない というわけではなく、もし可能ならばという感じです)

理想線はコントラスト比が1.3くらいで、チケット数の緑線は1.45くらい。WCAG2.0というアクセシビリティのガイドラインでは4.5以上がOKとなっています。

2021-03-17 04:35 UTC, yui-har commented
BurndownChart も（SearchableSelectbox と同様に）機能のOn/Offを切り替えることができると良いと思います。

2021-03-17 04:39 UTC, yui-har requested changes
BurndownChart も（SearchableSelectbox と同じように）機能のOn/Offを動的に切り替えることができると良いと思います。

2021-03-17 05:03 UTC, yui-har requested changes
Rubocopを実施したところ以下の警告が表示されました。
```
% bundle exec rubocop plugins/redmica_ui_extension/**/*.rb

9 files inspected, 20 offenses detected, 20 offenses auto-correctable
```

2021-03-17 05:09 UTC, takenory commented on lib/burndown_chart/versions_helper_patch.rb
> +        open = chart_start_date.step(line_end_date, step_size).collect{ |d| { :t => d.to_s, :y => issues.where("#{Issue.table_name}.created_on<=?", d.end_of_day).count - issues.open(false).where("#{I
step_sizeを設けることでチャート中のドットが増えすぎるのを回避しているのですが、最新(User.current.today)のチケット数がプロットされないのは誤解を生む原因になりそうですね 😓 
一方で、提案のコードのように User.current.today より先の日付にドットを置くのも避けたい...
そこで、以下のように、line_end_dateが必ずデータに含まれるようにして対処しようと考えています。
```suggestion
        total_closed = (chart_start_date.step(line_end_date, step_size).to_a + [line_end_date]).uniq.collect{ |d| { :t => d.to_s, :y => issues.where("#{Issue.table_name}.closed_on IS NULL OR #{Issue.table_name}.closed_on>=?", d.end_of_day).count } }
        open = (chart_start_date.step(line_end_date, step_size).to_a + [line_end_date]).uniq.collect{ |d| { :t => d.to_s, :y => issues.where("#{Issue.table_name}.created_on<=?", d.end_of_day).count - issues.open(false).where("#{Issue.table_name}.closed_on<=?", d.end_of_day).count } }
```
感想をお聞かせください。

2021-03-17 05:59 UTC, ishikawa999 commented on assets/burndown_chart/javascripts/burndown_chart.js
> +          time: { unit: "day", displayFormats: { day: 'YYYY-MM-DD' } },
Redmineのdate_format設定の中でも、チャートでは利用できない形式のものがいくつかあったのでYYYY-MM-DDに固定で進めることにします。

2021-03-23 02:12 UTC, takenory commented on lib/burndown_chart/versions_helper_patch.rb
> +        open = chart_start_date.step(line_end_date, step_size).collect{ |d| { :t => d.to_s, :y => issues.where("#{Issue.table_name}.created_on<=?", d.end_of_day).count - issues.open(false).where("#{I
コミット d3fb9a9ffe8bb4647279f08fef09e1254b36aee8 にて、プロットする日付にラインの終了日が常に含まれるように変更しました。

2021-03-23 02:31 UTC, takenory commented
@ishikawa999 

> 線の色が結構薄くて見づらく感じました。背景とのコントラスト比が結構低いようなので、もう少しはっきりした色に変えても良いんじゃないかなと思います。
> (Redmine内の他の場所でも同様にコントラスト比が低いところもありますし、もしデザイン的に支障が無ければという感じです)
> 
> 理想線はコントラスト比が1.3くらいで、チケット数の緑線は1.45くらい。WCAG2.0というアクセシビリティのガイドラインでは4.5以上がOKとなっています。

現状は、バージョン詳細画面でチケットの進捗状況を表すグラフと色（RGB: 186, 224, 186）を統一したものになります。
![image](https://user-images.githubusercontent.com/926014/112083776-009f6480-8bcb-11eb-80a9-c06d4122d3cb.png)

試しに、ガントチャート画面で使用されているバージョン線の色（RGB: 89, 195, 57）と統一すると以下のようになりました。
![image](https://user-images.githubusercontent.com/926014/112083479-7951f100-8bca-11eb-92a6-36141e088122.png)

画面全体の色調を考えると前者で良いように思いますが、チャートの見やすさを考えると後者が良いように思います。
改善ミーティングの際に意見を聞いてみて決めようと思います。

2021-03-24 00:35 UTC, takenory commented
> Rubocopを実施したところ以下の警告が表示されました。
> 
> ```
> % bundle exec rubocop plugins/redmica_ui_extension/**/*.rb
> 
> 9 files inspected, 20 offenses detected, 20 offenses auto-correctable
> ```

f73ebb247a811a64e7cab38ad792d80f2987f895 にて、警告を解消する変更を追加しました。

2021-03-24 00:49 UTC, yui-har commented
> > Rubocopを実施したところ以下の警告が表示されました。
> > ```
> > % bundle exec rubocop plugins/redmica_ui_extension/**/*.rb
> > 
> > 9 files inspected, 20 offenses detected, 20 offenses auto-correctable
> > ```
> 
> [f73ebb2](https://github.com/redmica/redmica_ui_extension/commit/f73ebb247a811a64e7cab38ad792d80f2987f895) にて、警告を解消する変更を追加しました。

OKです。警告が表示されないことを確認しました。

2021-03-24 01:47 UTC, takenory commented
> BurndownChart も（SearchableSelectbox と同じように）機能のOn/Offを動的に切り替えることができると良いと思います。

a37ff8efa50edb5f0963c1fde16b9d1e11738581 にて、バーンダウンチャートの表示/非表示を切り替える設定を追加しました。

2021-03-24 03:03 UTC, yui-har approved these changes
OKです。バーンダウンチャートの表示/非表示が切り替わることを確認しました。

2021-03-24 03:09 UTC, yui-har reviewed
@takenory  テスト test/helpers/versions_helper_patch_test.rb の実施方法は`rake test TEST=plugins/redmica_ui_extension/test/helpers/versions_helper_patch_test.rb`でよろしいのでしょうか。
> rake redmine:plugins:test でテストを実施したところ、このテストだけ動かなかったので。

2021-03-24 04:18 UTC, yui-har commented
以下のチケットをガントチャートに表示したのですけど、未完了が1件になっています。2件が正しいと思うのですけど。
子チケットは未完了の数にカウントされていないのでしょうか。

<pre>
#3: ステータス:New, 開始日:2019-09-17, 期日:2019-09-27
#109: ステータス:New, 開始日:2019-09-17, 期日:2019-09-27, #3の子チケット
</pre>

<img width="961" alt="ScreenShot 2021-03-24 13 11 59" src="https://user-images.githubusercontent.com/7232538/112253783-b25d9480-8ca2-11eb-9f21-17d43203a0b8.png">

2021-03-24 06:33 UTC, ishikawa999 commented
https://github.com/redmica/redmica_ui_extension/pull/6#issuecomment-805475114 に対する改善案(ざっくり)

version.due_date < User.current.today && !version.completed?の場合はchart_end_dateをUser.current.todayにする

2021-04-05 03:31 UTC, takenory commented
> [#6 (comment)](https://github.com/redmica/redmica_ui_extension/pull/6#issuecomment-805475114) に対する改善案(ざっくり)
> 
> version.due_date < User.current.today && !version.completed?の場合はchart_end_dateをUser.current.todayにする

Version#complated?は以下の実装となっており、期限（effective_dateあるいはdue_date）が設定されていることを前提としており、改善案の仕様については考慮が必要。

```ruby
  def completed?
    closed? || (effective_date && (effective_date < User.current.today) && (open_issues_count == 0))
  end
```

改めて検討したチャート終了日の仕様案

```ruby
# 終了していないチケットが0件 == 全てのチケットが終了
if version.open_issues_count == 0
  # [バージョンの期限, 最後に終了されたチケットの終了日].max
  chart_end_date = [version.due_date,
                    version.visible_fixed_issues.open(false).maximum(:closed_on).to_date].compact.max
# 終了していないチケットが0件でない
else
  # 終了しているチケットがない
  if version.visible_fixed_issues.open(false).empty?
    # [(バージョンの期限 || 本日), 最後に作成されたチケットの作成日].max
    chart_end_date = [(version.due_date || User.current.today),
                      version.visible_fixed_issues.maximum(:created_on).to_date].max
  # 終了しているチケットがある
  else
    # [(バージョンの期限 || 本日), 最後に作成されたチケットの作成日, 最後に終了されたチケットの終了日].max
    chart_end_date = [(version.due_date|| User.current.today),
                      version.visible_fixed_issues.maximum(:created_on).to_date,
                      version.visible_fixed_issues.open(false).maximum(:closed_on).to_date].max
  end
end
```

2021-04-06 02:53 UTC, ishikawa999 approved these changes

2021-04-06 02:54 UTC, merged